### ISSUE TITLE
[Module Listing Request]: `vaxee` new state manager

### ISSUE THREAD

**Issue by letstri** [nuxt/modules#1004]
### Description

`Vaxee` - is a new state manager for Vue 3 and Nuxt that uses basic Vue functions and SSR from Nuxt.

### Repository

https://github.com/letstri/vaxee

### npm

https://www.npmjs.com/package/vaxee

### Nuxt Compatibility

Nuxt 3

**Comment by amandesai01** [comment]
Create a PR and link the issue
