### ISSUE TITLE
add anime js module

### ISSUE THREAD

**Issue by blackinitial** [nuxt/modules#105]
hello, can you add this module https://github.com/ivodolenc/nuxt-animejs

**Comment by blackinitial** [comment]
Not yet for the icon 🤦🏻‍♂️

**Comment by ivodolenc** [comment]
Hi @Geminii @blackinitial, that would be great 😀  As for the icon, you can put the default one or by your choice.

Please consider adding [this](https://github.com/ivodolenc/nuxt-font-loader), [this](https://github.com/ivodolenc/nuxt-lazysizes) and [this](https://github.com/ivodolenc/nuxt-gsap-module) module as well. Of course if you find them useful and appropriate. No hard feelings 😉

**Comment by Geminii** [comment]
> Hi @Geminii @blackinitial, that would be great 😀 As for the icon, you can put the default one or by your choice.
> 
> Please consider adding [this](https://github.com/ivodolenc/nuxt-font-loader), [this](https://github.com/ivodolenc/nuxt-lazysizes) and [this](https://github.com/ivodolenc/nuxt-gsap-module) module as well. Of course if you find them useful and appropriate. No hard feelings 😉

Such a great job @ivodolenc :) 
Maybe it could be better to add an MR for these different modules separately ?

I think it could be better to provide an icon for your animejs module instead of default libraries category 😀

**Comment by ivodolenc** [comment]
@Geminii Default would be ok, at least for now 👌 😉

**Comment by ivodolenc** [comment]
@Geminii @pi0 Thanks for adding the module 🤝 👍

**Comment by pi0** [comment]
And nice works @ivodolenc keep up doing it 👍

**Comment by pareshpandit** [comment]
How does one install and integrate AnimeJS in Nuxt3? 
I tried treating it as a module as well as a plugin, but to no avail.
Also, in the best case scenario, we are getting the Window not Defined error, when it is referred to as a buildModule on Dev. Now, therein, I am not able to define it as a Client Side only module.
