### ISSUE TITLE
Wrong repository URL for `element-plus` module

### ISSUE THREAD

**Issue by wazolab** [nuxt/modules#1051]
# Description
![image](https://github.com/user-attachments/assets/6543e008-615d-45aa-a42f-068d27f39de1)
Source: https://nuxt.com/modules/element-plus

Link to the Github repository actually redirects to Element Plus repo: https://github.com/element-plus/element-plus instead of Nuxt Element Plus repo: https://github.com/element-plus/nuxt-element-plus

**Comment by manniL** [comment]
PR welcome to fix that 👍🏻
