### ISSUE TITLE
[Module Listing Request]:`@primevue/nuxt-module`

### ISSUE THREAD

**Issue by tugcekucukoglu** [nuxt/modules#1056]
### Description

Replace `nuxt-primevue` with `@primevue/nuxt-module`

### Repository

https://github.com/primefaces/primevue/tree/master/packages/nuxt-module

### npm

https://www.npmjs.com/package/@primevue/nuxt-module

### Nuxt Compatibility

Nuxt 3

**Comment by atinux** [comment]
Happy to open a PR @tugcekucukoglu ?

**Comment by tugcekucukoglu** [comment]
My bad, it seems I did not tag the PR: https://github.com/nuxt/modules/pull/1057
