### ISSUE TITLE
snipcart-nuxt

### ISSUE THREAD

**Issue by TariikHr** [nuxt/modules#107]
hello folks 
i've read that there is a module snipcart-nuxt but i can't find it on the nuxt-modules website ?

any ideas please

**Comment by f3ltron** [comment]
thanks @TariikHr for creating the issue I was going to :)

**Comment by TariikHr** [comment]
@f3ltron All Thanks to you for your amazing Work

**Comment by Geminii** [comment]
@f3ltron @TariikHr Reality is coming 🚀
