### ISSUE TITLE
Add DruxtJS and relevant modules.

### ISSUE THREAD

**Issue by Decipher** [nuxt/modules#118]
DruxtJS is a modular framework built on top of Nuxt that consumes the Drupal JSON:API to offer Fully Decoupled Drupal instances.

Modules:
DruxtJS - https://github.com/druxt/druxt.js / https://druxtjs.org
DruxtJS Blocks - https://github.com/druxt/druxt-blocks / https://blocks.druxtjs.org
DruxtJS Breadcrumb - https://github.com/druxt/druxt-breadcrumb / https://breadcrumb.druxtjs.org
DruxtJS Entity - https://github.com/druxt/druxt-entity / https://entity.druxtjs.org
DruxtJS Menu - https://github.com/druxt/druxt-menu / https://menu.druxtjs.org
DruxtJS Router - https://github.com/druxt/druxt-router / https://router.druxtjs.org
DruxtJS Schema - https://github.com/druxt/druxt-schema / https://schema.druxtjs.org
DruxtJS Site - https://github.com/druxt/druxt-site / https://site.druxtjs.org
DruxtJS Views - https://github.com/druxt/druxt-views / https://views.druxtjs.org

**Comment by Atinux** [comment]
Thanks for the issue @Decipher 

I believe adding `druxt` would be enough for the website. We plan to open the integration for more details informations, I think there we could list Druxt and its modules :)
