### ISSUE TITLE
dead repos

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#12]
- https://github.com/nuxt-community/material-icons-module (alternative https://github.com/anteriovieira/nuxt-material-design-icons ?)
- https://github.com/jmblog/nuxt-netlify-http2-server-push (support for Netlify http2 server push has been dropped -  https://community.netlify.com/t/why-was-http-2-server-push-support-dropped/14770/4)
- https://github.com/nuxt-community/modules/tree/master/packages/bulma
- https://github.com/nuxt-community/modules/tree/master/packages/plugin-utils

**Comment by Geminii** [comment]
Hello @pi0 👋 

Do you think it could be a great idea to add a script which check links of all integrated modules 🤔 
More maintainability will be necessary if we add always more modules.

**Comment by pi0** [comment]
Hi @Geminii ❤️ 

That could be good idea. Probably we can also fetch last publish date for npm package.

Something i'm not sure is that some modules do not actually need updates for a long time. But we may leverage maintainers.app stats for scoring.

Above list is mostly a hand-written list of module that should not exist in list

**Comment by Geminii** [comment]
Thanks for your answer 😀

I did a quick script to verify all modules and it still all of these are available ❤️

Do you think we can close this issue or you want to integrate them into the list ? 

I noticed it miss some another modules particularly in UI category from `create-nuxt-app` : 
- chakra-ui
- element-ui
- framevuerk
- iview
- tachyons
- vuesax 

If you need some help to improve this repository, i'm available to help you 👍

**Comment by pi0** [comment]
https://github.com/nuxt-community/webpackmonitor-module
