### ISSUE TITLE
Add Vue Formulate

### ISSUE THREAD

**Issue by justin-schroeder** [nuxt/modules#121]
We just published [Vue Formulate](https://vueformulate.com/) 2.5.1 which includes a Nuxt module for easier installation and configuration.

https://vueformulate.com/guide/installation/#nuxt

Would be great to get it on the list 👍

**Comment by Atinux** [comment]
Happy to land a PR for it @justin-schroeder ?

I know we have Formkit for Nuxt 3 that works well!

**Comment by justin-schroeder** [comment]
Ha! Honestly at this point I don’t think I want to encourage people to use Vue Formulate. I'll close this issue, but thanks for the consideration 👍
