### ISSUE TITLE
Sorting by "recently added" 

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt/modules#139]
Hi 👋🏻 

I would be nice for nuxt lovers to be able to know when a new module is added, easier to keep up with new modules and helpful for learning curve.

Thanks.

**Comment by tevfiksirin** [comment]
+1

**Comment by dosstx** [comment]
I was looking for this feature, but did not see it.  I suggest we add it, if possible!

**Comment by Geminii** [comment]
Hi 👋 

Already purpose it in this PR [82](https://github.com/nuxt/modules/pull/82). 
Feel free to upvote 😇
