### ISSUE TITLE
modules path resolve bug

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/modules#15]
Hi guys, I testing modules support in my project and nuxt build process is warn me with error with path resolve to nuxt module.

![image](https://cloud.githubusercontent.com/assets/2588730/26581388/e91c696e-4544-11e7-8225-19fb20a66081.png)

As you can see, the path was wrong, or webpack alias is not working.
How to fix that?

**Comment by pi0** [comment]
Hi @ruslankonev. This is strange, i'm currently getting it working in my local env. Are you using linked dependencies?

**Comment by pi0** [comment]
Also can you pelase check that actually axios.plugin.* file exists in `.nuxt` dir of project?

**Comment by ruslankonev** [comment]
Yeah, plugin file was exists. How I can link dependencies?
![image](https://cloud.githubusercontent.com/assets/2588730/26581610/1c967db0-4546-11e7-8551-2074090a5e48.png)

**Comment by pi0** [comment]
(For development you may use `npm/yarn link` command in cloned repository and running `npm link @nuxtjs/axios` on test project, but that needs some additional runtime flags) It is still strange! Would you please share your repo link?

**Comment by ruslankonev** [comment]
That's need some time.. but `yarn link` is not help to resolve path.
