### ISSUE TITLE
Google Tag Manager - Lodash Syntax Incorrect

### ISSUE THREAD

**Issue by samsherwood** [nuxt/modules#17]
When translating the template for the Google Tag Manager module, lodash does not pick up the options passed into the module, due to the formatting being incorrect on the plugin.

For instance:
`'<%= options.layer ?>'`

Should be:
`'<%= options.layer %>'`

**Comment by pi0** [comment]
@samsherwood Thanks for report. Actually we need more tests on this module. Feel free opening PR for fixes.

**Comment by samsherwood** [comment]
Noted! Right now, not 100% sure that's the only issue, as my build did not end up adding in the options are the template was updated. Just ended up being an empty string.

**Comment by pi0** [comment]
Meanwhile for testing you can easily copy/paste module files into your project modules directory and require using `~/modules/google-tag-manager` :)

**Comment by samsherwood** [comment]
Much appreciated! Wasn't sure what convention to follow in that regard.

**Comment by samsherwood** [comment]
Found the other issue in the index.js -- options are being passed as 'currentOptions' which then is not expected by the template engine. Where the 'addPlugin' occurs, need to assign currentOptions to options.

**Comment by pi0** [comment]
new version published
