### ISSUE TITLE
Add nuxt headway

### ISSUE THREAD

**Issue by l-portet** [nuxt/modules#178]
Hey there, I made a module to easily integrate the Headway changelog widget into a Nuxt app.

Feel free to add it :)

https://github.com/l-portet/nuxt-headway

**Comment by Atinux** [comment]
Looks good to me, can you follow the instructions how to add a module? https://github.com/nuxt/modules#add-or-update-repository

**Comment by l-portet** [comment]
Sure, PR opened at #184
