### ISSUE TITLE
alternatives

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#2]
- https://github.com/microcipcip/cookie-universal
- https://github.com/lupas/nuxt-fire
- https://github.com/vaso2/nuxt-fontawesome
- https://github.com/wemake-services/nuxt-imagemin
- https://github.com/kdydesign/nuxt-moment-module
- https://github.com/vicbergquist/nuxt-sanity
- https://github.com/gaven/nuxt-svg-sprite-module
- https://github.com/nurdism/nuxtjs-electron
- https://github.com/vaso2/nuxt-fullpage.js (vs https://github.com/vaso2/fullpage-nuxt :eyes: )

**Comment by Atinux** [comment]
What should we do regarding them?

**Comment by debs-obrien** [comment]
https://github.com/vicbergquist/nuxt-sanity this one is now deprecated according to Victoria in favor of our one

**Comment by mathe42** [comment]
I wrote my own vuetify, leaflet and typescript module and would love to add them (at least the leaflet as I think my module is better as it treeshakes the components with nuxt/components...)

**Comment by pi0** [comment]
Hi @mathe42 would you please create two issues for leaflet and vuetify linking to their corresponding repos?
