### ISSUE TITLE
Markdown Module

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#20]
Related to nuxt/nuxt.js#836

**Comment by pi0** [comment]
Module is ready !
https://github.com/nuxt/modules/tree/master/modules/markdownit 
http://npmjs.com/package/@nuxtjs/markdownit

@alidcastano If possible please give your feedback.

**Comment by alidcastano** [comment]
Just gave it a try and it worked! Thanks.

Does it also allow vue components to be used inside Markdown files? (I previously used [vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader) for this.)

**Comment by pi0** [comment]
Happy hearing working. Nop but it can be another module! PRs always welcome ;)

**Comment by iamdubx** [comment]
Absolutely not working.
