### ISSUE TITLE
Modules list content dissapears scrooling down

### ISSUE THREAD

**Issue by chefjuanpi** [nuxt/modules#206]
Bug: When you scroll down on the modules list at [https://nuxtjs.org/modules/](https://nuxtjs.org/modules/) the modules list content disappears making it impossible to see all modules.

Browsers tested:

- Edge
<img width="374" alt="nuxtModules1" src="https://user-images.githubusercontent.com/7308580/139588744-fdb270ad-a9b1-4d9a-9108-22380d5d5954.png">

 
- Firefox
<img width="686" alt="nuxtModulesFirefox" src="https://user-images.githubusercontent.com/7308580/139588746-66155d77-8eb4-4033-a84f-27aa04daefc4.png">

 - Chrome
<img width="664" alt="nuxtModulesChrome" src="https://user-images.githubusercontent.com/7308580/139588753-1c3922a9-a77f-4b7c-9b6a-38f92262b255.png">

**Comment by pi0** [comment]
Hi @chefjuanpi. I couldn't reporoduce this issue anymore on edge (windows) 95.0.1020.53 and  96.0.1054.29 . Please ping me to reopen if you still experience it.
