### ISSUE TITLE
axios module

### ISSUE THREAD

**Issue by dinho-afsn** [nuxt/modules#22]
I try use modules in nuxt but erros TypeError: Cannot read property '$axios' of undefined
i try use module https://github.com/nuxt/modules/tree/master/modules/axios
Could you give me a help on how to use the modules in nuxtjs? tanks!

**Comment by pi0** [comment]
Hi @dinho-afsn . Will publish a fix soon.

**Comment by dinho-afsn** [comment]
thanks for the answer. Is there any other way to add the token in the header in all requests with axios?

**Comment by SinisaG** [comment]
+1 for short demo of how to use modules with `nuxtjs`. Looking forward to more documentation and modules! Thanks for great work @pi0

**Comment by pi0** [comment]
Hi. [Axios](https://github.com/nuxt/modules/tree/master/modules/axios) module just bumped to to 2.0. Please take a look at docs ;)

**Comment by pi0** [comment]
Working glitch demo : 

https://glitch.com/edit/#!/zest-ring?path=pages/index.vue:22:1
https://zest-ring.glitch.me/
