### ISSUE TITLE
Migrate to Nuxt 3

### ISSUE THREAD

**Issue by antfu** [nuxt/modules#224]
- [x] Rewrite to use `<script setup>` and composition api
- [ ] Break down 	index.vue
- [ ] Check modules compatibility

**Comment by pi0** [comment]
Some suggestions:
- It would be nice using bridge CAPI first
- We can disable incompatible modules during migration
- We can do `index.vue` refactor after migrating to nuxt 3

**Comment by productdevbook** [comment]
https://github.com/nuxt/framework/issues/1036 Also, this problem still persists. It can be a little annoying to constantly refresh the browser while coding a design.

**Comment by antfu** [comment]
No longer relevant, as the website has moved to nuxt.com
