### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Atinux** [nuxt/modules#228]
This need to be improved ☺️
![image](https://user-images.githubusercontent.com/904724/142083654-1df3195e-e50f-4966-a15a-5bd88aa58b03.png)

**Comment by Atinux** [comment]
Cc @antfu

**Comment by r9mp** [comment]
@antfu May I do it?

**Comment by antfu** [comment]
@r9mp feel free to drop an PR and we could improve it together

**Comment by r9mp** [comment]
@antfu First PR to solve this issue #230 

I tried to look at the header, but I'm not sure what should be done. Please tell me what you think about:
- The icon on the right (computer) should be dark mode or light mode depending on browser mode.
- On phones and tablets, the search bar should be on second line, logo and icon with a flex between.
- On lg+ same as now
- The padding seems to be broken on md+, the padding should match "Explore Nuxt Modules" padding

**Comment by antfu** [comment]
The current status

![image](https://user-images.githubusercontent.com/11247099/142171877-97ad1627-33b7-4b44-9264-e573c15f58af.png)

I think we will have quite a few things to improve

**Comment by r9mp** [comment]
@antfu If "Explore Nuxt Modules" block displays the same way in phone and tablet, is it ok for you?

**Comment by antfu** [comment]
@r9mp I have already done it :)

**Comment by r9mp** [comment]
@antfu Can I try doing the header or you're on it?

**Comment by antfu** [comment]
Do you mean the searh bar? I just pushed a few refactor on them just FYI.

Please join the Discord: https://discord.gg/hRVDffdA

**Comment by r9mp** [comment]
I sent you a direct message on Dicord.
