### ISSUE TITLE
Using contributors in cards

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#253]
In order to simplify maintenance of DB and also including more contributors credits in modules website, instead of `maintainers` we can pick few first contributors from nuxt API (https://api.nuxtjs.org/api/github/contributors/nuxt-community/axios-module)

TODO: Improve bots filtering

**Comment by antfu** [comment]
Do we sort them by contributions? I guess we could display up to 4 or 5 contributors in the UI

**Comment by pi0** [comment]
4-5 seems nice. Not sure about sorting it directly comes from github API but I think yes they sort it by number of commits to main branch
