### ISSUE TITLE
Module [@nuxtjs/google-analytics,[object Object]] should export a function

### ISSUE THREAD

**Issue by ztrayner** [nuxt/modules#27]
Followed the instructions I found [here](https://github.com/nuxt/modules/tree/master/modules/google-analytics), but I get the following error:

> nuxt build && backpack build
> 
> [nuxt] Building...
> [nuxt] Module [@nuxtjs/google-analytics,[object Object]] should export a function
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! wld@1.0.0 build: `nuxt build && backpack build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the wld@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

My nuxt.config.js has the following (UA has been replaced) 

`    modules: [
        ['@nuxtjs/google-analytics', { ua: 'UA-XXXXXXX-X' }]
    ]`

**Comment by pi0** [comment]
@ztrayner What version of nuxt.js are you currently using?

**Comment by ztrayner** [comment]
`"nuxt": "~1.0.0-alpha1"`

**Comment by pi0** [comment]
Babel style syntax for options (arrays) is only supported in latest alpha. Please simply upgrade to `nuxt@1.0.0-alpha.4` and problem should resolved :)

**Comment by ztrayner** [comment]
I swear I just upgraded to alpha1!  Haha.  You guys move fast.  Thanks!
