### ISSUE TITLE
Add front-matter and content modules for static sites and blogs

### ISSUE THREAD

**Issue by alidcastano** [nuxt/modules#29]
So I previously opened up this [issue](https://github.com/nuxt/nuxt.js/issues/747) on the main Nuxt repo, but its more appropriate to reopen it here.

---

I plan on using nuxt generate to create static sites and blogs. Other alternates, obviously, are Jekyll, Hexo, Hugo, etc.

Currently, like the mentioned alternatives, nuxt provides:

- layouts or templates
- components or partials
- dynamic urls or routing
- assets loading (css, images, etc.)

However, the main features it does not provide:

- Data files for reusable information that can be used inside pre-compiled files (this can be done inside HTML templates locally with the data component property, but there is no global data configurations that can be used inside markdown files before they are compiled as vue components)

- Front-matter/metadata that facilitates content organization (e.g. by date, title, category etc.)

I feel like these two features would be a great addition to modules. I was going to try to hack a solution for myself, but maybe I can abstract it away so that it can be more useful. Let me know what you think and if you have any feedback on how they should be implemented.

**Comment by pi0** [comment]
Hi @alidcastano Thanks for your intereset in nuxt/modules. 
Actually without modules, dynamic content are possible too, If your review nuxtjs.org source code, it is dynamically loading markdowns from a remote API :) But idea of creating a dynamic blog module for nuxt would be awesome. Actually @znck has already started same idea and is working on a Jekyll blog module implementation :) So we may wait for his work stablized and working on a same thing.
About providing dynamic content. As already mentioned, one possible way is we register a dynamic api endpoint using modules `addServerMiddleware` to respond with proper json for each page. Something like this:
```js
this.addServerMiddleware({
      path: '/api/posts',
      async handler (req, res, next) {
        let post_id = req.query.id
        // fetch post / load and parse markdown
       // reponse with json
      }
  })

```
This has an advantage of *dynamic blog posts* even after build phase. We may also register some store plugins / routes and templates for zero code blog experience :) Anyway this was just an example approach we may do even better things.

**Comment by znck** [comment]
> Data files for reusable information that can be used inside pre-compiled files (this can be done inside HTML templates locally with the data component property, but there is no global data configurations that can be used inside markdown files before they are compiled as vue components)

I didn't get this. Do you want `{{ .... }}` interpolation in markdown/other files?

> Front-matter/metadata that facilitates content ...

Already supporting in in the blog module.

https://github.com/znck/nuxt-module-blog
Just started! I hope by next week, this would be usable.

**Comment by alidcastano** [comment]
Hey @znck,

Sorry if I wasn't clear, yes, I mean a similar implementation to `Jekyll` where you have global `data files` and can use them via  `{{ }}` interpolation.

I'm actually started working on a similar solution, as well. But I started it from the webpack loader side first! 

Here's the project: https://github.com/alidcastano/vue-content-loader.

I'm working off `vue-markdown-loader` and adding the ability to extract front matter/metadata and add it to component `data`. Then I was planning on adding nuxt modules to facilitate content organization. 

Perhaps we can share ideas and maybe even work on a similar solution together.

**Comment by znck** [comment]
To use `{{ }}` interpolation in `.md` files, we have to generate a temporary component (`.vue` file).


In https://github.com/znck/nuxt-module-blog 🙄,  I'm generating sorta JSON API that can be served with an `express` middleware or statically accessed.

**Comment by alidcastano** [comment]
@pi0 I missed your comment earlier. I've seen the Nuxt.js site. I used it as inspiration for the documentation site I built for my other project [Ency.js](http://encyjs.alidcastano.com/).

But personally, I didn't like remotely loading content. I preferred to have it built locally using a webpack loader (or nuxt module that interacts with `nuxt generate`). For Ency's site, I used `vue-markdown-loader` to compile Markdown files into vue components. The added benefit of this is that you can use demo components inside the markdown files. 

As mentioned above, I'm going to implement a similar idea with `vue-content-loader` so that it can load front matter and parse the markdown files. Then I'll use nuxt-modules to facilitate the organization of content.

**Comment by alidcastano** [comment]
I'd love to use Nuxt to serve a similar purpose to React's `Gatsby`. The beauty about Nuxt and `nuxt generate` is that it already does most of the heavy work. It's about filling in the missing gaps.

**Comment by alidcastano** [comment]
@znck So you're implementing a solution similar to what @pi0 mentioned? Where you load the content remotely and parse it and respond with the proper JSON? Is there a reason you choose this approach over generating it all locally, given that we already happen `nuxt generate` available to built the site.

**Comment by pi0** [comment]
@alidcastano I don't exactly mean using a remote API. See using only loaders has drawback that it only works good for statically generated blogs. We could simply serve emitted assets using a nuxt serverMiddleware. This will work with both `nuxt generate` and `nuxt start` too :) What's do you think? And why you still may prefer static loaders?

**Comment by alidcastano** [comment]
Ah, honestly I was only thinking about static generated sites/blogs. But I don't see why having the content compiled in advance and rendered the same as a normal page would be a negative even for server rendered sites. There's going to be a build step with webpack loaders regardless. Unless there's something I'm misunderstanding, which could very well be the case.

**Comment by znck** [comment]
Generated site would serve initial pages, then on subsequent page visits, a XHR would fetch the required content (rather than whole page) and render it. Sorta SPA with statically generated files serving as SSR.

**Comment by alidcastano** [comment]
@znck I've made a PR https://github.com/nuxt/modules/pull/34 for a nuxt content module and have continued this conversation there.
