### ISSUE TITLE
search not working as it should

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/modules#29]
The search is behaving weird. If I search for stylelint or cloudinary I get results for anything but them. If I search for Maya I get loads of results. I am not sure what the search is basing itself on but it is not working how it should. 

Should be:
search by author,  module name, maybe even module description

**Comment by Atinux** [comment]
I agree on this, I think we can remove `lunr` to only keep a simple `indexOf(q) !== -1`

**Comment by Atinux** [comment]
I will revert the commit actually.

![Screenshot 2020-10-20 at 15 52 32](https://user-images.githubusercontent.com/904724/96595755-4e4a3500-12ec-11eb-8be6-31322dfed176.png)
![Screenshot 2020-10-20 at 15 52 36](https://user-images.githubusercontent.com/904724/96595775-51452580-12ec-11eb-85ec-ea958e9498e2.png)
