### ISSUE TITLE
Filters not working on live website

### ISSUE THREAD

**Issue by wc-davide** [nuxt/modules#298]
Filters are no longer working on the live website: https://modules.nuxtjs.org/

Clicking on any "Nuxt version", "Categories" or "Order by" results in this console error:
![image](https://user-images.githubusercontent.com/46521712/152805126-ba6ca80c-18cd-4343-8786-0dae3f3cb11d.png)

Tested with (both desktop):
- Chrome 97.x
- Brave 98.x

In the past days it was working fine so I guess it has something to do with the recent commits... maybe https://github.com/nuxt/modules/commit/3e402d37ce37e21e8e9f0d6cd439bbe84ae7c04a ?

**Comment by antfu** [comment]
Thanks, it should be fixed with the Nuxt 3 migration
