### ISSUE TITLE
missing integrations

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#3]
Here is list of some missing integrations. Some have related toturials but not module

# ui
- element ui
- iview

# cms
- Forestry / TinaCMS
- notion
- Directus
- KeystoneJS
- ghost

# database
- hasura
- Postgraphile
- FaunaDB
- prisma

# analytics
- Facebook Pixel

# reporting
- Bearer.sh
- nuxt-Memwatch
- Calibreapp.com

# images
- TwicPics

# Payments
- paypal
- checkout.com

# ecommerce
- snipcart
- Magento
- woo commercec
- reaction commerce
- vue storefront

**Comment by debs-obrien** [comment]
how do we showcase these? i know we have type module and this would be type integration but do we showcase that or user just sees it when it goes to detail page which only has description, learn more button, perhaps article and no github info or what do you suggest? @pi0 @alexchopin @Atinux

**Comment by pi0** [comment]
This needs supporting manual integrations (markdown only instructions) still not sure about refering to template repos because integrations guide how to _add_ into existing project.

**Comment by pi0** [comment]
Outdated
