### ISSUE TITLE
Website performances

### ISSUE THREAD

**Issue by Atinux** [nuxt/modules#30]
- Group classes repeated
![unknown](https://user-images.githubusercontent.com/904724/97013328-391e1200-1549-11eb-966e-301a930aa0c5.png)

- Use https://github.com/maoberlehner/vue-lazy-hydration

- List only the first 12 modules and lazy render more on scroll

**Comment by richardsaseun14** [comment]
Can I take this issue?

**Comment by Atinux** [comment]
Sure @richardsaseun14

**Comment by Geminii** [comment]
PR : https://github.com/nuxt/modules/pull/48

**Comment by Geminii** [comment]
@Atinux i think we can closed this one 👍
