### ISSUE TITLE
Search on website does not appropriatly search tittles

### ISSUE THREAD

**Issue by ZainW** [nuxt/modules#302]
# Problem

search shows unrelated resuts when trying to search by module's name

## Reproduction examples

navigate to https://modules.nuxtjs.org/

1.  type `axios` into search, result: stylelint, expected: axios https://modules.nuxtjs.org/?q=axios
2.  type `pwa` into search, result: webpack-profile, expected: pwa https://modules.nuxtjs.org/?q=pwa
3.  type `vueuse` into search, result: headway, expected: vueuse https://modules.nuxtjs.org/?q=vueuse

**Comment by ZainW** [comment]
im looking into the issue to see if i can solve it myself

at first glance it should work as fuse is being fed correct things and the filteredModules computed also looks fine at first glance

I will try and investigate and get it solved

**Comment by clemcode** [comment]
Thank you for the report @ZainW 

Were you able to investigate more? Otherwise I'll take a look at it.

**Comment by antfu** [comment]
Should be fixed now :)
