### ISSUE TITLE
How to set axios token for authorization

### ISSUE THREAD

**Issue by ImadBoumzaoued** [nuxt/modules#31]
Hello sorry to make this an issue, I've tried to make this work

```Exposes setToken function to $axios so we can easily and globally set authentication tokens.```

but without any luck can you please  explain how to make it work form a store mutation.

Thanks a lot

**Comment by pi0** [comment]
Hi. Thanks for currently lack of it's documentation. Actually i've just left it until auth module is ready. For setting authentication token, anywhere that you have access to `$axios` (see docs) can call like this: 
```js
// This will add `Authentication: Bearer ....`  header to all requests
$axios.setToken('Token from API or Cookies', 'Bearer')
```

**Comment by ImadBoumzaoued** [comment]
Hey thanks for the reply, I don't know what I'm doing wrong but when I do it like this

`this.$axios.setToken(token, false)`

I get setToken is not a function

**Comment by pi0** [comment]
Hmm i can't test now but seems it should be attached to prototype instead until bug resolved please use an alternative like this: `$axios.defaults.headers.common.Authorization= toekn`

**Comment by ImadBoumzaoued** [comment]
Ok I'll use the alternative solution.
Thanks a lot :)

**Comment by pi0** [comment]
`setToken` docs are ready and working :)
https://github.com/nuxt/modules/tree/master/modules/axios#helpers

**Comment by indiecore-fm** [comment]
@pio the link leads me to a 404

**Comment by Flyer3d** [comment]
@pi0 Link doesn't work! 404

**Comment by kaungmyatlwin** [comment]
@indiecore-fm @Flyer3d https://auth.nuxtjs.org/api/auth.html

**Comment by rahul9874563210** [comment]
@kaungmyatlwin can you give example using nuxt/auth module for external API authentication with custom function.

detail issue is here 
https://github.com/nuxt-community/auth-module/issues/216
