### ISSUE TITLE
Plausible module is not compatible yet

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/modules#324]
`vue-plausible` is listed as compatible with Nuxt 3, but I think it shouldn't be listed yet. At first glance it seems like it's working, but it actually breaks all anchor tags once activated.

**Comment by pi0** [comment]
Hi! Current website is using this module and Nuxt 3. Maybe reporting issue to the upstream would be a good idea?

**Comment by toniengelhardt** [comment]
Hi @pi0, thanks for the reply! With upstream you mean the vue-plausible repo? 

The issue is already reported here: https://github.com/moritzsternemann/vue-plausible/issues/18

**Comment by toniengelhardt** [comment]
It looks like the problem is related to outbound link tracking (see https://github.com/moritzsternemann/vue-plausible/issues/18#issuecomment-1063841416). Disabling the feature resolves the issue, closing this!
