### ISSUE TITLE
nuxt-community/supabase-module

### ISSUE THREAD

**Issue by procrates** [nuxt/modules#349]
Definitly add supabase module for nuxt 3!
[https://supabase.nuxtjs.org/](https://supabase.nuxtjs.org/)
[https://github.com/nuxt-community/supabase-module](https://github.com/nuxt-community/supabase-module)

**Comment by Atinux** [comment]
Fixed in https://github.com/nuxt/modules/commit/806e19d778e558696f2402a94cd9465c4019dea1

Thanks @procrates

**Comment by procrates** [comment]
Perfect! Sorry looked at another api website.. [isnuxt3ready.owln.ai](isnuxt3ready.owln.ai)

And now I just noticed its been favored for modules.nuxtjs :D great job! Love Nuxt especially 3! Deploying nuxt 3 website as I write this:D

**Comment by owlnai** [comment]
> Perfect! Sorry looked at another api website.. [isnuxt3ready.owln.ai](isnuxt3ready.owln.ai)

Sorry for the confusion! I [archived that site](https://github.com/owlnai/isnuxt3ready/issues/17#issuecomment-953270935) last year. I've just added a 301 redirect to modules.nuxtjs.org 😅

**Comment by procrates** [comment]
Good job on it anyways! Thank you for the fix:D
