### ISSUE TITLE
this.$axios different than store.$axios

### ISSUE THREAD

**Issue by smith64fx** [nuxt/modules#35]
Hello,
I just found out that this.$axios has a baseUrl whereas store.$axios has no baseUrl!

Is this a bug?

How to reproduce...

Just make this in some component:

```
    console.log(this.$axios.defaults.baseURL)
    console.log(this.$store.$axios.defaults.baseURL)
```

the first one is undefined, the second one is http://localhost:3000 (in my case)

**Comment by pi0** [comment]
Thanks @smith64fx for report :) Next release would be available soon.
