### ISSUE TITLE
Production build fails with pwa module

### ISSUE THREAD

**Issue by smith64fx** [nuxt/modules#37]
Hey guys :)

I just tried the pwa module, it's really awesome!

when I do "npm run build", it builds.

But when I do "npm start" it tells me:
```
No build files found, please run `nuxt build` before launching `nuxt start`
```

But the build files are there.. Is this a bug or did I do something wrong?

**Comment by pi0** [comment]
Hi. I'm not sure this problem is with pwa module. Are you sure `.nuxt/dist` is available after build? Any repo to reproduce this issue?

**Comment by smith64fx** [comment]
Hey @pi0 
I think we messed up some things :)

We used the analyze function:
```
  build: {
    analyze: true,
  }
```

I didn't know that the analyze function prevents the build itself!

Sorry bro!

**Comment by pi0** [comment]
That's ok :) Thanks for report maybe better including this fact in docs.
