### ISSUE TITLE
Add `nuxt-svgo`

### ISSUE THREAD

**Issue by cpsoinos** [nuxt/modules#371]
There wasn't a SVG module compatible with Nuxt 3 yet, so I made one: https://github.com/cpsoinos/nuxt-svgo
- leverages [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader) for Vite builds 
- leverages [svg-to-vue-component](https://github.com/egoist/svg-to-vue-component) for Webpack builds:

**Comment by Atinux** [comment]
Thanks @cpsoinos 

Do you mind creating an online playground on StackBlitz for it?

Also, it seems the badges images are broken:

![Screenshot 2022-06-21 at 15.10.00@2x.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_06_21_at_15_10_00_2x_65af82a376.png)

**Comment by cpsoinos** [comment]
Thanks @Atinux ! I've added a StackBlitz playground link to the readme and fixed the badges:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/10081464/174840770-289f5dfc-04c4-4648-a1ba-256ec09a6ab8.png">

**Comment by Atinux** [comment]
Thanks, I also think that https://github.com/cpsoinos/nuxt-svgo/blob/main/src/module.ts#L38 should use `options` instead of `config`.

Lastly, I would name the option key `svgo` instead of `svgoOptions`

**Comment by Atinux** [comment]
I would also add `svgoConfig` in the defaults too don't you think? https://github.com/cpsoinos/nuxt-svgo/blob/main/src/module.ts#L22

**Comment by Atinux** [comment]
Otherwise looks good to me, can you open a PR to this repo? https://github.com/nuxt/modules#add-or-update-repository

**Comment by cpsoinos** [comment]
Thanks! Added `svgoConfig` to the defaults as an empty object, and opened a PR: https://github.com/nuxt/modules/pull/391
