### ISSUE TITLE
Add Dash.js to module

### ISSUE THREAD

**Issue by shba007** [nuxt/modules#392]
Hi I am currently working on VoD Web app in Nuxt. I am using MPEG-DASH for ABR(Adaptive Bitrate) for this I found [Dash.js](https://github.com/Dash-Industry-Forum/dash.js). But there is no module for Dash.js. Anyone interested to create or suggest a module for Nuxt?

**Comment by danielroe** [comment]
This is a worthy initiative but not really an issue to be reported in this repo. I'd suggest asking around on https://discord.nuxtjs.org.
