### ISSUE TITLE
Sort and Order By

### ISSUE THREAD

**Issue by imanmalekian31** [nuxt/modules#404]
Sort and Order By have a problem !! I couldn't figure it out in local because data is mocked.
And also I checked with production API data but it was ok! It's so weird.

<img width="885" alt="Screen Shot 1401-04-24 at 16 08 14" src="https://user-images.githubusercontent.com/58827166/179216270-7e4978e6-6b8e-47b9-8ff4-cbb4b0b4ec0d.png">

**Comment by Atinux** [comment]
cc @antfu

**Comment by antfu** [comment]
Duplicated, please keep track on #403
