### ISSUE TITLE
add `nuxt-particles`

### ISSUE THREAD

**Issue by Phatza** [nuxt/modules#408]
Hi everyone,

There wasn't a Particles module compatible with Nuxt 3 so i made one : https://github.com/Phatza/nuxt-particles

Thanks in advance,
Regards

**Comment by Atinux** [comment]
Thank you, but for this kind of plugins, I think it's more than enough to have an example of a Nuxt 3 demo using the particules plugin instead :blush:

**Comment by Phatza** [comment]
Hi guys,
Copy that, I will do it that way.

Thx guys,
Reply
