### ISSUE TITLE
adding modules to nuxt3-rc6 using yarn introduces peer dependency warningss

### ISSUE THREAD

**Issue by AliQ80** [nuxt/modules#411]
hello,

I added two modules to nuxt 3 (yarn add @formkit/nuxt) and (yarn add @pinia/nuxt) and got these warnings

warning "@formkit/nuxt > @formkit/vue@1.0.0-beta.9" has unmet peer dependency "vue@^3.2.1".

warning "@pinia/nuxt > pinia@2.0.17" has unmet peer dependency "vue@^2.6.14 || ^3.2.0".
warning "@pinia/nuxt > pinia > vue-demi@0.13.5" has unmet peer dependency "vue@^3.0.0-0 || ^2.6.0".

both require vue, should I add vue or will it create conflicts in nuxt 3 

is there a way to fix these warnings?

thank you

**Comment by danielroe** [comment]
It will not create conflicts with Nuxt. Note that this is the repository for the https://modules.nuxtjs.org website and probably not the best place for support. Try https://github.com/nuxt/framework/discussions or https://discord.nuxtjs.org.

**Comment by AliQ80** [comment]
thank you for the quick reply and the tip

I posted here because what I'm installing are modules
but good to know where to post next time
