### ISSUE TITLE
Adding nuxtjs-darkmode-js-module

### ISSUE THREAD

**Issue by sandoche** [nuxt/modules#42]
Hi,

I recently created https://github.com/sandoche/nuxtjs-darkmode-js-module
It adds https://github.com/sandoche/Darkmode.js to Nuxt

Would you like to add it?

**Comment by Geminii** [comment]
Hi @sandoche 
Currently, there is already an official module named [color-mode](https://color-mode.nuxtjs.org/) which is available. 
But i think you can purpose a PR to bring your module inside :) 

Each module is representing by a simple yml file. 
It's really simple to add your own ;)
