### ISSUE TITLE
Add 'nuxt-umami'

### ISSUE THREAD

**Issue by ijkml** [nuxt/modules#421]
Hi,
I created a wrapper for [Umami Analytics](https://umami.is) compatible with Nuxt 3.

It is a rewrite of [nuxt-umami-module](https://github.com/joe-pritchard/nuxt-umami-module) but for Nuxt 3 (and theoretically, Nuxt 2).
`nuxt-umami-module` has an SSR issue, and I don't think it is being maintained anymore. I also tried contacting Joe Pritchard but got no response.

Repo: https://github.com/ijkml/nuxt-umami
npm: https://www.npmjs.com/package/nuxt-umami

I would appreciate any help/feedback!

**Comment by Atinux** [comment]
Nice work @ijkml 

Can you open a PR to add the module?

See how to add a repo: https://github.com/nuxt/modules#add-or-update-repository

**Comment by ijkml** [comment]
Thanks!

Opened a PR: https://github.com/nuxt/modules/pull/427

**Comment by ijkml** [comment]
Many thanks, @danielroe 
Looking at the entry on the website, the module appears not to support Nuxt 3...

![Screenshot of Umami entry in nuxt modules website](https://user-images.githubusercontent.com/52390439/192166393-056740fc-c7ec-4e75-a167-98e189c26ea5.png)

Could it be because of this line?
https://github.com/nuxt/modules/blob/a45b62d0e1f4dd5cd36b0e6ce77e4671271b63c6/modules/umami.yml#L15
Maybe the modules website don't recognize rc versions yet?

**Comment by danielroe** [comment]
Good catch. In this repo it's just ^3.0.0.

**Comment by ijkml** [comment]
That was fast 😅
Okay, no problem.
I'll be around if there's anything I can do to help
