### ISSUE TITLE
add `vuestic-ui`

### ISSUE THREAD

**Issue by m0ksem** [nuxt/modules#424]
Hey. We have a VuesticUI module for nuxt3 :
https://github.com/epicmaxco/vuestic-ui/tree/develop/packages/nuxt
https://vuestic.dev/en/getting-started/nuxt

Please, take a look. Feedback appreciated :)

**Comment by pi0** [comment]
Added some suggestions: https://github.com/epicmaxco/vuestic-ui/issues/2238 otherwise look fantastic!
