### ISSUE TITLE
README is broken

### ISSUE THREAD

**Issue by odanado** [nuxt/modules#439]
On github.com, README.md renders as follows.

<img width="727" alt=" 2022-09-04 1 01 23" src="https://user-images.githubusercontent.com/6040962/188278753-5e1d01b7-8623-4456-8051-1f7cc92a098b.png">

But here's what's actually happening.
<img width="821" alt=" 2022-09-04 1 07 11" src="https://user-images.githubusercontent.com/6040962/188278930-eb476dcd-1acf-42a0-8b27-20d73cfb2704.png">

The text after `requires.bridge: true` is not displayed.

**Comment by odanado** [comment]
Maybe, You need to change `true|optional` to `true\|optional`.

**Comment by antfu** [comment]
PR welcome!
