### ISSUE TITLE
"Cannot find module 'home/.../dist/module.cjs'" error when trying to start a vanilla module dev environment

### ISSUE THREAD

**Issue by rajosch** [nuxt/modules#456]
I am trying to develop a nuxt module, utilizing the test environment, but I cannot start the 'playground' to do local testing.
The follwing error orrurs:

<pre><span style="background-color:#CC0000"><font color="#333333"> ERROR </font></span> Cannot start nuxt:  Cannot find module &apos;/home/.../dist/module.cjs&apos;. Please verify that the package.json has a valid &quot;main&quot; entry                                      <font color="#88807C">21:38:22</font>

  <font color="#88807C">at </font>tryPackage (<font color="#06989A">node:internal/modules/cjs/loader:364:19</font>)
  <font color="#88807C">at </font>Function.Module._findPath (<font color="#06989A">node:internal/modules/cjs/loader:577:18</font>)
  <font color="#88807C">at </font>Function.Module._resolveFilename (<font color="#06989A">node:internal/modules/cjs/loader:942:27</font>)
  <font color="#88807C">at </font>Function.resolve (<font color="#06989A">node:internal/modules/cjs/helpers:108:19</font>)
  <font color="#88807C">at </font>_resolve (<font color="#06989A">node_modules/jiti/dist/jiti.js:1:243302</font>)
  <font color="#88807C">at </font>jiti (<font color="#06989A">node_modules/jiti/dist/jiti.js:1:245428</font>)
  <font color="#88807C">at </font>playground/nuxt.config.ts:2:32
  <font color="#88807C">at </font>Object.jiti (<font color="#06989A">node_modules/jiti/dist/jiti.js:1:247502</font>)
  <font color="#88807C">at </font>resolveConfig (<font color="#06989A">node_modules/c12/dist/index.mjs:220:21</font>)
  <font color="#88807C">at </font>loadConfig (<font color="#06989A">node_modules/c12/dist/index.mjs:104:40</font>)
  <font color="#88807C">at </font>async loadNuxtConfig (<font color="#06989A">node_modules/@nuxt/kit/dist/index.mjs:686:18</font>)
  <font color="#88807C">at </font>async loadNuxt (<font color="#06989A">node_modules/nuxt/dist/index.mjs:1616:19</font>)
  <font color="#88807C">at </font>async loadNuxt (<font color="#06989A">node_modules/@nuxt/kit/dist/index.mjs:732:19</font>)
  <font color="#88807C">at </font>async load (<font color="#06989A">node_modules/nuxi/dist/chunks/dev.mjs:6767:23</font>)
  <font color="#88807C">at </font>async Object.invoke (<font color="#06989A">node_modules/nuxi/dist/chunks/dev.mjs:6828:5</font>)
  <font color="#88807C">at </font>async _main (<font color="#06989A">node_modules/nuxi/dist/cli.mjs:50:20</font>)
</pre>

Here are the commands I used in order to recreate the issue:

```rb
npx nuxi init -t module <name>

cd <name>

yarn

yarn dev
```

npx: 8.15.0
Nuxi 3.0.0-rc.11

**Comment by danielroe** [comment]
You need to run `yarn dev:prepare` first.
