### ISSUE TITLE
Debounce the search input

### ISSUE THREAD

**Issue by Voltra** [nuxt/modules#467]
Currently the search input is not debounced and thus feels very unresponsive, in addition to the API requests generated per character as evidenced by the provided screenshot:

<img width="960" alt="Screenshot showing that a pageView event is generated per search character" src="https://user-images.githubusercontent.com/25990549/195812355-525247db-4a98-4101-9542-b25eb5f027d3.png">

**Comment by Atinux** [comment]
Happy to open a PR?
