### ISSUE TITLE
Add nuxt-headlessui

### ISSUE THREAD

**Issue by P4sca1** [nuxt/modules#475]
I created a new Nuxt module, which provides a convenient integration with [Headless UI](https://headlessui.com).

GitHub: https://github.com/P4sca1/nuxt-headlessui
NPM: nuxt-headlessui

The main advantage is that you can use dynamic auto imports, which was not easily possible with the components / auto import option of nuxt, because of the directory structure of `@headlessui/vue` (it uses `.js` files instead of Vue SFCs and groups multiple components in a single file).

**Comment by danielroe** [comment]
Would you be able to prepare a PR to add it to https://modules.nuxtjs.org ?
