### ISSUE TITLE
add module: pinia-plugin-persistedstate

### ISSUE THREAD

**Issue by prazdevs** [nuxt/modules#512]
Hey :) I recently created a nuxt module to make this pinia plugin integration much easier with nuxt. It'd be amazing to have it listed in the module list :D

The base plugin was a port of vuex-persistedstate, with some pinia features :)

Here is the repo of the plugin : https://github.com/prazdevs/pinia-plugin-persistedstate
Nuxt module code is here : https://github.com/prazdevs/pinia-plugin-persistedstate/tree/main/packages/nuxt
And documentation is here : https://prazdevs.github.io/pinia-plugin-persistedstate/

thanks :)

**Comment by CodeDredd** [comment]
@prazdevs I was so kind and made an PR for you since i made one for my pinia plugin ;-)
