### ISSUE TITLE
[Module Listing Request]: Add nuxt3-notifications as module

### ISSUE THREAD

**Issue by windx-foobar** [nuxt/modules#564]
### Description

This Module is Nuxt 3 compatible release of  [@kyvg/vue3-notification](https://github.com/kyvg/vue3-notification)

### Repository

https://github.com/windx-foobar/nuxt3-notifications

### npm

https://www.npmjs.com/package/nuxt3-notifications

### Nuxt Compatibility

Nuxt 3

**Comment by flozero** [comment]
hey @windx-foobar Looking at your modules dist folder is there is it expected ? Also there is no doc about it. try to use as much as possible [conventional commit ](https://www.conventionalcommits.org/en/v1.0.0/#specification) to help you on the release versioning

**Comment by windx-foobar** [comment]
@flozero Thanks for the answer! Changed commits under [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#specification). Can you see again my repo?:)
