### ISSUE TITLE
[Module Listing Request]: Add `nuxt-calendly` module

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/modules#568]
### Description

I've created the `nuxt-calendly` module recently, which can be used to directly integrate calendly in your app. 

Currently, no such plugin exists for nuxt. There is a simple one for vue existing `https://www.npmjs.com/package/calendly-vue`. The benefit over is that `nuxt-calendly` is a real nuxt/kit module, has complete documentation (even more than calendlys own docs) and offers:

## Features

- 💪 &nbsp;Type safe integration of Calendly into your project
- 🧱 &nbsp;Auto-loaded components for [Inline Widget](https://nuxt-calendly.vercel.app/components/inline-widget), [Popup Widget](https://nuxt-calendly.vercel.app/components/popup-widget), and [Popup Button](https://nuxt-calendly.vercel.app/components/popup-button)
- 🕹️ &nbsp;A [`useCalendly()`](https://nuxt-calendly.vercel.app/composables/use-calendly) composable to access all of calendly's [widget.js](https://assets.calendly.com/assets/external/widget.js) methods.
- 🔥 &nbsp;A [`useCalendlyEventListener()`](/composables/use-calendly-event-listener) composable to listen to certain [events](https://developer.calendly.com/api-docs/ZG9jOjI3ODM2MTAz-notifying-the-parent-window) provided by calendly.
- 🛝 &nbsp;Visit the [Playground](https://nuxt-calendly-playground.vercel.app/) to try out all the functionalities of the module.
- ⚛️ &nbsp;Inspired by [react-calendly](https://github.com/tcampb/react-calendly)

## Links

- [✨ &nbsp;Release Notes](https://github.com/madebyfabian/nuxt-calendly/blob/main/CHANGELOG.md)
- [📖 &nbsp;Documentation](https://nuxt-calendly.vercel.app)
- [🛝 &nbsp;Playground](https://nuxt-calendly-playground.vercel.app/)
- [📦 &nbsp;NPM](https://www.npmjs.com/package/nuxt-calendly)

### Repository

https://github.com/madebyfabian/nuxt-calendly

### npm

https://www.npmjs.com/package/nuxt-calendly

### Nuxt Compatibility

Nuxt 3

**Comment by danielroe** [comment]
Beautiful! A PR would be very welcome.
