### ISSUE TITLE
[Module Listing Request]:  `@nuxtjs/snipcart`

### ISSUE THREAD

**Issue by flozero** [nuxt/modules#572]
Description
This Module is Nuxt 3 compatible release of [@nuxtjs/snipcart](https://github.com/nuxt-community/snipcart-module). It also have a fully typescript support

Repository
https://github.com/nuxt-community/snipcart-module

npm
https://www.npmjs.com/package/@nuxtjs/snipcart

Nuxt Compatibility
Nuxt 3

**Comment by danielroe** [comment]
A PR would be welcomed. Also, it would be nice to move you to new `nuxt-modules` organisation - will DM.
