### ISSUE TITLE
Electron module support!

### ISSUE THREAD

**Issue by caoxiemeihao** [nuxt/modules#579]
I wrote an Electron module for Nuxt, and I want it to appear in the Module section of the official website.

👉 [nuxt-electron](https://github.com/caoxiemeihao/nuxt-electron)

**Comment by Atinux** [comment]
Can you open a PR for it by following ou readme?

Also, could you please add the `meta` and `defaults` properties to your module as well? https://github.com/nuxt/starter/blob/5ae9fa0243480b29ac37d7dc7c2b410cf3400f28/src/module.ts#L7-L12

**Comment by caoxiemeihao** [comment]
> Can you open a PR for it by following ou readme?

Yep!

**Comment by caoxiemeihao** [comment]
@Atinux 
https://github.com/caoxiemeihao/nuxt-electron/commit/142307b8353058df26173659f48a5608cae577d7
It is okay?

**Comment by Atinux** [comment]
Why not adding `include: ['electron']` by default?

Also you may want to publish a new release for this on npm :)

**Comment by caoxiemeihao** [comment]
Ha ha, I will release the latest version tomorrow morning! 😁

**Comment by caoxiemeihao** [comment]
@Atinux `nuxt-electron` v0.4.0 is out! https://github.com/caoxiemeihao/nuxt-electron/pull/7

**Comment by Atinux** [comment]
Beautiful logo! I opened a pr and issue on your repo

**Comment by caoxiemeihao** [comment]
Is there any more work I need to do?
