### ISSUE TITLE
[Module Listing Request] Nuxt-Snackbar

### ISSUE THREAD

**Issue by modbender** [nuxt/modules#597]
# Description
Nuxt Snackbar provides a wrapper for [vue3-snackbar](https://github.com/craigrileyuk/vue3-snackbar) to be used with Nuxt.js

# Features
- Easy to integrate
- Instantly usable Snackbar, no config required
- Options to fully customize Snackbar

# Repository
https://github.com/modbender/nuxt-snackbar

# npm Package
https://www.npmjs.com/package/nuxt-snackbar

**Comment by Atinux** [comment]
Could you open a PR by following the instructions in the readme?

**Comment by modbender** [comment]
> Could you open a PR by following the instructions in the readme?

Sure, will check

**Comment by modbender** [comment]
@Atinux Done, please check #598
