### ISSUE TITLE
[Module Listing Request]: `nuxt-chatgpt`

### ISSUE THREAD

**Issue by SchnapsterDog** [nuxt/modules#604]
### Description

[ChatGPT](https://openai.com/) integration for [Nuxt 3](https://nuxt.com/).

This user-friendly module boasts of an easy integration process that enables seamless implementation into any [Nuxt 3](https://nuxt.com/) project. With type-safe integration, you can integrate [ChatGPT](https://openai.com/) into your [Nuxt 3](https://nuxt.com/) project without breaking a sweat. Enjoy easy access to the send method through the useChatgpt() composable. Additionally, the module guarantees security as requests are routed through a [Nitro Server](https://nuxt.com/docs/guide/concepts/server-engine), thus preventing the exposure of your API Key.

Features
- Easy implementation into any [Nuxt 3](https://nuxt.com/) project.
- Type-safe integration of Chatgpt into your [Nuxt 3](https://nuxt.com/) project.
- Provides a useChatgpt() composable that grants easy access to the send method.
- Ensures security by routing requests through a [Nitro Server](https://nuxt.com/docs/guide/concepts/server-engine), preventing the API Key from being exposed.
- It is lightweight and performs well.

### Repository

https://github.com/schnapsterdog/nuxt-chatgpt

### npm

https://www.npmjs.com/package/nuxt-chatgpt

### Nuxt Compatibility

Nuxt 3

**Comment by danielroe** [comment]
This looks nice. I've added a few comments and PR upstream.

**Comment by SchnapsterDog** [comment]
> This looks nice. I've added a few comments and PR upstream.

Thanks a lot @danielroe for the detailed feedback. Appreciate your time. The master branch is updated with your PR upstream. New version is bumped.
