### ISSUE TITLE
Nuxt Content Assets

### ISSUE THREAD

**Issue by davestewart** [nuxt/modules#632]
### Description

Nuxt Content Assets enables locally-located assets in [Nuxt Content](https://content.nuxtjs.org/).

It's compatible with any Nuxt Content project or theme (including [Docus](https://github.com/nuxt-themes/docus)) and also plays well with [Nuxt Image](https://github.com/nuxt/image).

User experience:

- co-locate assets with content files
- reference assets using relative paths
- supports any format (image, video, doc)

Developer experience:

- works with tags and custom components
- works in markdown and frontmatter
- file watching and asset live-reload
- image size injection
- zero config

### Repository

https://github.com/davestewart/nuxt-content-assets

### npm

https://www.npmjs.com/package/nuxt-content-assets

### Nuxt Compatibility

Nuxt 3

**Comment by davestewart** [comment]
The other option is I just migrate this into Nuxt Content and PR...

**Comment by Atinux** [comment]
Happy to open a PR for adding the module @davestewart ?

**Comment by davestewart** [comment]
Sure!
