### ISSUE TITLE
[Module Listing Request]: `nuxt-mongoose`

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/modules#633]
### Description
It simplifies the use of Mongoose in your project, it comes with a database playground for nuxt-devtools (helps with creating resources(crud api endpoints with model schema))

*note: I'm sure there's a lot to improve*

### Repository

https://github.com/arashsheyda/nuxt-mongoose

### npm

[npmjs.com/package/nuxt-mongoose](https://www.npmjs.com/package/nuxt-mongoose)

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR @arashsheyda ?
