### ISSUE TITLE
Wide Angle Analytics

### ISSUE THREAD

**Issue by jrozanski** [nuxt/modules#645]
### Description

This module is a wrapper for [Wide Angle Analytics](https://wideangle.co) web analytics client library. It leverages a Vue package also authored by our team, the [wideangle-vuejs](https://www.npmjs.com/package/wideangle-vuejs). 

### Repository

https://github.com/inputobjects/wideangle-nuxt

### npm

https://www.npmjs.com/package/wideangle-nuxt

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR following the readme?

**Comment by jrozanski** [comment]
Thanks @Atinux, will give it a go :)

**Comment by jrozanski** [comment]
PR created https://github.com/nuxt/modules/pull/653

**Comment by jrozanski** [comment]
cc @Atinux
