### ISSUE TITLE
[Module Listing Request]: `nuxt-twemoji`

### ISSUE THREAD

**Issue by Yizack** [nuxt/modules#650]
### Description

Nuxt module for implementing Twemoji. Component for rendering emojis as SVG elements or PNG images, by character, codepoint or definition. 

### Repository

https://github.com/Yizack/nuxt-twemoji

### npm

https://www.npmjs.com/package/nuxt-twemoji

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR?

**Comment by Yizack** [comment]
@Atinux Sure! PR open, thank you!
