### ISSUE TITLE
Nuxt UIkit

### ISSUE THREAD

**Issue by samk-dev** [nuxt/modules#681]
### Description

This module is a wraper for UIkit framework [https://getuikit.com/docs/introduction](https://getuikit.com/docs/introduction)

### Repository

https://github.com/samk-dev/nuxt-uikit3

### npm

https://www.npmjs.com/package/@samk-dev/nuxt-uikit3

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Thanks for the module.

Do you mind renaming it to avoid having the letter `3` inside? What happens when Nuxt 4 comes out?

**Comment by samk-dev** [comment]
Hi Sebastian, thank you for your time. Sorry for the confusion, the 3 stands for UIkit 3, there's a v4 in the making that's why I named it uikit3. 

If you think it's better to remove it I can rename it. What's the better approach to that to not breaking current npm install when they need to update. or renaming the repo name is enough?

**Comment by Atinux** [comment]
You can publish the package with the new name and deprecate the old one to mention the new one @samk-dev

**Comment by samk-dev** [comment]
Atinux thanks again for your time.

 I would prefer not to break current installations, even if the number of installs is currently very small. It's frustrating experience for users. I believe such a change would be more justified when UIkit 4 is released. I am gonna skip listing this module in Nuxt module directory, as I have other modules for nuxt to list waiting to finish some polishing.
 
 thanks 🙏
