### ISSUE TITLE
nuxt-fontagon

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#69]
- https://github.com/kdydesign/nuxt-fontagon
- https://github.com/nuxt-community/awesome-nuxt/pull/436

(awaiting for more star/downloads)

**Comment by kdydesign** [comment]
@Atinux Hi.
Online example of using nuxt-fontagon.
Thank you.

**Comment by kdydesign** [comment]
@Atinux 
Added codeandbox link.
https://github.com/kdydesign/nuxt-fontagon

Thank you.
