### ISSUE TITLE
[Module Listing Request]: vue-email

### ISSUE THREAD

**Issue by Flowko** [nuxt/modules#698]
Description
[vue-email](https://vue-email.vercel.app/)

Vue Email is inspired by [react-email](https://react.email/), it allows us create templates using the vue framework, with components that help us build templates easily and fast.

I'd like to propose adding this module, to allow users to easily create emails using vue component and logic

Features
- 🧩 Build email templates with Vue components
- 📨 [Integrates with many email providers](https://vue-email.vercel.app/integrations/nodemailer.html)
- 🧪 Tested against popular email clients
- 🎨 [Supports Tailwind CSS](https://vue-email.vercel.app/components/tailwind.html)

Links
- 📖 [Docs](https://vue-email.vercel.app/)
- 📦 [NPM](https://www.npmjs.com/package/vue-email)
- 🧪 [Demo](https://vue-email-demo.vercel.app/)

Nuxt Compatibility
Nuxt 3

**Comment by danielroe** [comment]
Opened https://github.com/Dave136/vue-email/pull/11.

**Comment by Flowko** [comment]
its merged

**Comment by danielroe** [comment]
PR welcome 🙏

**Comment by Flowko** [comment]
PR open

**Comment by Flowko** [comment]
how long does it take to show on the modules website 😊 ?
