### ISSUE TITLE
Add nuxt-seo-meta module to generate seo metadata easy

### ISSUE THREAD

**Issue by ihavecoke** [nuxt/modules#70]
explore https://modules.nuxtjs.org i just found `nuxt-social-meta` module that's cool.

when i use this module in my project, haven't found how to set to different page with different seo metadata. so create module called `nuxt-seo-meta` which can set metadata when you need custom your page seo.

name: nuxtjs-seo-meta
description: Generate seo metadata simplely 
repo: ihavecoke/nuxt-seo-meta
npm: nuxtjs-seo-meta
icon: 'http://public.mixbo.cn/nuxtjs-seo-meta.png?t'
github: 'https://github.com/ihavecoke/nuxt-seo-meta'
category: SEO
type: 3rd-party

**Comment by Geminii** [comment]
Hi @ihavecoke 👋 

If you want to integrate your module, you can purpose a PR using : 
```
yarn sync seo-meta ihavecoke/nuxtjs-seo-meta
```

About the name, i recommand you to name it just `seo-meta` into modules explorer 😉
For your icon, it's recommanded to respect the dimension of 40*40px 😀

Suggestion for your module : 
For new module, it highly recommanded to use `buildModules` (https://nuxtjs.org/docs/2.x/directory-structure/modules#buildmodules) as far as possible

**Comment by ihavecoke** [comment]
> Hi @ihavecoke 👋
> 
> If you want to integrate your module, you can purpose a PR using :
> 
> ```
> yarn sync seo-meta ihavecoke/nuxtjs-seo-meta
> ```
> 
> About the name, i recommand you to name it just `seo-meta` into modules explorer 😉
> For your icon, it's recommanded to respect the dimension of 40*40px 😀
> 
> Suggestion for your module :
> For new module, it highly recommanded to use `buildModules` (https://nuxtjs.org/docs/2.x/directory-structure/modules#buildmodules) as far as possible

thks，let me create PR first 😀

**Comment by ihavecoke** [comment]
@Geminii i have created PR with your suggestion 😀

**Comment by ihavecoke** [comment]
@Geminii have someone review my PR https://github.com/nuxt/modules/pull/71 :)

**Comment by Geminii** [comment]
> @Geminii have someone review my PR #71 :)

Yes, it's @Atinux to do it :) 
Before to validate a PR, it deploy on Vercel to check the module integration

**Comment by ihavecoke** [comment]
> > @Geminii have someone review my PR #71 :)
> 
> Yes, it's @Atinux to do it :)
> Before to validate a PR, it deploy on Vercel to check the module integration

ok i got it, thks 😀

**Comment by ihavecoke** [comment]
@Atinux Thks for you  review. i just resloved the issue  https://github.com/ihavecoke/nuxt-seo-meta/issues/1. can you review again ? :)
