### ISSUE TITLE
Basic auth module

### ISSUE THREAD

**Issue by kgierke** [nuxt/modules#724]
### Description

This module gives the option to protect the whole site with a simple basic auth mechanism. Multiple users can be added and certain routes can be whitelisted.

### Repository

https://github.com/kgierke/nuxt-basic-auth

### npm

https://www.npmjs.com/package/@kgierke/nuxt-basic-auth

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Nice, happy to open a PR @kgierke ?

**Comment by Intevel** [comment]
@Atinux Created one!

**Comment by kgierke** [comment]
Ah wow, sorry didn't had the time to come back to this one yet. Thanks for creating the PR!

**Comment by Intevel** [comment]
This can be closed. /cc @Atinux
