### ISSUE TITLE
nuxt-vcalendar

### ISSUE THREAD

**Issue by samk-dev** [nuxt/modules#726]
### Description

Integrates [VCalendar](https://vcalendar.iol) into Nuxt with zero config auto importing both components and from the config it has more option to import what's needed.

### Repository

https://github.com/samk-dev/nuxt-vcalendar

### npm

https://www.npmjs.com/package/@samk-dev/nuxt-vcalendar

### Nuxt Compatibility

Nuxt 3

**Comment by danielroe** [comment]
PR would be welcome 🙏

**Comment by samk-dev** [comment]
> PR would be welcome 🙏 

@danielroe  thank you for the replay. Where should I open the PR?

**Comment by danielroe** [comment]
Against this repository. You can see some info about how to do that in the README.
