### ISSUE TITLE
nuxt-mdi

### ISSUE THREAD

**Issue by ERPedersen** [nuxt/modules#738]
### Description

This module adds a component for displaying icons with [Material Design Icons](https://pictogrammers.com/library/mdi/).

### Repository

https://github.com/ERPedersen/nuxt-mdi

### npm

https://www.npmjs.com/package/nuxt-mdi

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR @ERPedersen ?
