### ISSUE TITLE
How can i remove html comments generated from nuxtjs loops and if/else and all other things.

### ISSUE THREAD

**Issue by seetpalsingh** [nuxt/modules#757]
I am getting lots of loop html comments and conditional html comments in page source from browser.

can you please provide me proper solutions in nuxt3.

see attachment for example.

<img width="793" alt="Scherm_afbeelding 2023-08-29 om 18 26 12" src="https://github.com/nuxt/modules/assets/4477434/fa2ed564-e41f-40fc-80ba-e1142cf74b92">

**Comment by Atinux** [comment]
Wrong repo
