### ISSUE TITLE
Sort by last updated

### ISSUE THREAD

**Issue by larzon83** [nuxt/modules#76]
Can we have a sort by last updated? Thx

**Comment by Geminii** [comment]
It could be a great idea but currently we don't have the information about last update for each module. 
They are only extract from npm but not update. 
A solution could be create a script to iterate on each of them to get lastUpdated value for current module then purpose a sort in this direction. 
What do you think about it @pi0 ?

**Comment by pi0** [comment]
Having last updated would be nice since we can also use it for rss feed output

**Comment by larzon83** [comment]
> Last updated as last released at?

Yes. For me at least

**Comment by Geminii** [comment]
> I guess we can use the `pushed_at` attribute from GH API: https://api.github.com/repos/nuxt/image
> 
> Would be nice to have the last release date from NPM, but I struggled to find the API endpoint.

GET on http://registry.npmjs.org/nuxt-image and we get extract the `time.modified` which seems to be the last published version

**Comment by Geminii** [comment]
So i will update script for new upload 😀 
And of course update all current modules 👍

**Comment by Geminii** [comment]
What do you think about to add the released date into module card ?
Your opinion is welcome @pi0 about to add this improvement 😀

**Comment by pi0** [comment]
@Geminii That would be cool!

Only a small note that we may need to migrate this project at a point of time to serverless in order to have updated stats. Temporary solution could be GH actions with crontab to trigger deploy everyday...

**Comment by Geminii** [comment]
> @Geminii That would be cool!
> 
> Only a small note that we may need to migrate this project at a point of time to serverless in order to have updated stats. Temporary solution could be GH actions with crontab to trigger deploy everyday...

Yes i think it's a good point. 
However, we probably need to improve the `yarn sync` all modules. During the development, i saw that some modules had a different description for example. We could maybe add a parameter to synchronize only released date ?

**Comment by pi0** [comment]
Historically, this project and sync command was designed to publish modules database which then can be served by website. Fetching on development, slows down build and i think having latest tags isn't important for dev. With serverless, we can do some more refactors for caching API :)

**Comment by pi0** [comment]
Initial idea for package was to allow offline support and implement meta fetching directly in website. We might snapshot from prod API and filter-out frequently changing fields like stars...

**Comment by Geminii** [comment]
> * Using @nuxt/modules as a package, it should not include stars, download and last release

Currently, these informations are extracted during the build into `dist/modules.json`. 
However, we can always remove them. But this assumes that if an external service retrieves all the modules and wishes to offer a similar service regarding the release date for example, it is up to it to call npm to retrieve recent information no ?

**Comment by pi0** [comment]
> However, we can always remove them. But this assumes that if an external service retrieves all the modules and wishes to offer a similar service regarding the release date for example, it is up to it to call npm to retrieve recent information no ?

Actually anyone can do it but purpose of published will be mainly for nuxt-cli for `nuxt module <add>` command for having installation meta-data which is currently not in db...

**Comment by Geminii** [comment]
> Actually anyone can do it but purpose of published npm package will be mainly for nuxt-cli for `nuxt module <add>` command for having installation meta-data which is currently not in db...

Ok i understand. I will open an issue to remove these extra fields (stars, download and last release) into build step and purpose a PR in this direction 👍

**Comment by pi0** [comment]
@Geminii It would be nice if can wait for serverless migration. I'm working on it now :)

**Comment by Geminii** [comment]
No problem, don't hesitate to remind me once it's in place 😀
