### ISSUE TITLE
Add nuxt-use-sound

### ISSUE THREAD

**Issue by Tahul** [nuxt/modules#77]
Hello :)

I just created a Nuxt module to add sound effects to your app easily.

You can find it here: [nuxt-use-sound](https://github.com/Tahul/nuxt-use-sound)

If there is anything that needs to be fixed inside the package itself or its documentation, please let me know!

Thank you again for all your amazing work on Nuxt.

**Comment by Geminii** [comment]
Hey @Tahul 👋 

Nice work on your module. 
To be good to inject your module `$sounds` to respect Nuxt module best practices.
cf: [https://nuxtjs.org/docs/2.x/directory-structure/plugins#inject-in-root--context](url) 

Then you can purpose a PR to directly add it into the module explorer 👍

**Comment by Tahul** [comment]
Hello @Geminii ;

As stated in the documentation you linked: "The $ will be prepended automatically to the key."

Should I still add it myself too? From the example I already reach the injected context through "$sounds".

Thank you for your answers @Geminii :)
