### ISSUE TITLE
nuxt-auth-sanctum

### ISSUE THREAD

**Issue by manchenkoff** [nuxt/modules#772]
### Description

This module provides a simple way to use Laravel Sanctum with Nuxt by leveraging cookies-based authentication. SSR-ready!

### Repository

https://github.com/manchenkoff/nuxt-auth-sanctum

### npm

https://www.npmjs.com/package/nuxt-auth-sanctum

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR?

**Comment by manchenkoff** [comment]
Sure thing, will do 👍
