### ISSUE TITLE
[Module Listing Request]: `nuxt-interpolation`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/modules#782]
### Description

Pretty essential package when you are building a blog-like platform where editors can create internal-link to other post inside WYSIWYG.
https://github.com/daliborgogic/nuxt-interpolation

### Repository

https://github.com/daliborgogic/nuxt-interpolation

### npm

https://www.npmjs.com/package/nuxt-interpolation

### Nuxt Compatibility

Nuxt 2

**Comment by Atinux** [comment]
Happy to open a PR @mrleblanc101 ?
