### ISSUE TITLE
[Module Listing Request]: `nuxt-3-interpolation`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/modules#783]
### Description

Pretty essential package when you are building a blog-like platform where editors can create internal-link to other post inside WYSIWYG.
https://github.com/daliborgogic/interpolation

### Repository

https://github.com/daliborgogic/interpolation

### npm

https://www.npmjs.com/package/nuxt3-interpolation

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR?

**Comment by mrleblanc101** [comment]
@Atinux Added both on the same PR
