### ISSUE TITLE
[Module Listing Request]: `@vueform/builder-nuxt`

### ISSUE THREAD

**Issue by adamberecz** [nuxt/modules#795]
### Description

This module is a wrapper for [`@vueform/builder`](https://github.com/vueform/builder).

### Repository

https://github.com/vueform/builder-nuxt

### npm

https://www.npmjs.com/package/@vueform/builder-nuxt

### Nuxt Compatibility

Nuxt 3

**Comment by adamberecz** [comment]
In case you need a logo: https://vueform.com/images/logo.svg

**Comment by Atinux** [comment]
Happy to open a PR?
