### ISSUE TITLE
[Module Listing Request]: `nuxt-doppler`

### ISSUE THREAD

**Issue by JamieCurnow** [nuxt/modules#800]
### Description

Integrates Doppler secrets into the Nuxt build. Will fetch secrets from doppler and then map them to the nuxt runtimeConfig like env vars at build time. This means you only need to maintain one env var in your build process - the Doppler service token. Then all env vars / secrets are managed through Doppler.

### Repository

https://github.com/JamieCurnow/nuxt-doppler

### npm

https://www.npmjs.com/package/nuxt-doppler

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR @JamieCurnow 

Instructions are in the radme

**Comment by JamieCurnow** [comment]
Thanks @Atinux PR here #829 🙌
