### ISSUE TITLE
[Module Listing Request]: Adds email sending capability to a Nuxt.js app. 

### ISSUE THREAD

**Issue by imcm7** [nuxt/modules#803]
### Description

Adds email sending capability to a Nuxt.js app. Adds a server route, an injected variable, and uses nodemailer to send emails.

Does not work for static sites (via nuxt generate) because the module creates a server route.

### Repository

https://github.com/dword-design/nuxt-mail/issues/209

### npm

https://npmjs.org/package/nuxt-mail

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Can you open a PR please? You have the instructions in the readme about how to create a PR
