### ISSUE TITLE
[Module Listing Request]: Laravel Precognition for Nuxt

### ISSUE THREAD

**Issue by sot1986** [nuxt/modules#807]
### **Description**
This module nuxt-laravel-precognition https://github.com/sot1986/nuxt-laravel-precognition allows the interaction with Laravel Precognition Middleware (server side form validation without duplication of validation rules) without need of installing axios library.

It replicates the vue plugins from Laravel team, improving typescript support and it is optimized to be used with Nuxt (not in Inertia.js context)

I would like to give it some visibility now that it has been used from quite a while.

### **Repository**
https://github.com/sot1986/nuxt-laravel-precognition

### **npm**
https://www.npmjs.com/package/nuxt-laravel-precognition

### **Compatibility**
Nuxt3

**Comment by Atinux** [comment]
Sounds good, happy to open a PR @sot1986 

You can follow the readme to see how to do it!
