### ISSUE TITLE
[Module Listing Request]:```use-bootstrap```

### ISSUE THREAD

**Issue by simplise-developer** [nuxt/modules#844]
### Description

This module is a wrapper to front-end framework based on Nuxt3 and Bootstrap5

### Repository

https://github.com/simplise/use-bootstrap

### npm

https://www.npmjs.com/package/usebootstrap

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Feel free to open a PR by following the readme @simplise-developer
