### ISSUE TITLE
[Module Listing Request]: `nuxt-openapi-docs-module`

### ISSUE THREAD

**Issue by s00d** [nuxt/modules#846]
### Description

Generate pages from OpenAPI specifications

### Repository

https://github.com/on-org/nuxt-openapi-docs-module

### npm

https://www.npmjs.com/package/nuxt-openapi-docs-module

### Nuxt Compatibility

Nuxt 2, Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR for it @s00d ?
