### ISSUE TITLE
[Module Listing Request]: `nuxt-marquee`

### ISSUE THREAD

**Issue by hanzydev** [nuxt/modules#850]
### Description

A lightweight Nuxt 3 component that harnesses the power of CSS animations to create silky smooth marquees.

### Repository

https://github.com/hanzydev/nuxt-marquee

### npm

https://www.npmjs.com/package/nuxt-marquee

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Feel free to open a PR for it :)
