### ISSUE TITLE
[Module Listing Request]: `nuxt-bezier`

### ISSUE THREAD

**Issue by 50rayn** [nuxt/modules#859]
### Description

This module integrates the [@noction/vue-bezier](https://github.com/Noction/vue-bezier) component with Nuxt 3. This is a module which contains reusable transition components.

### Repository

https://github.com/50rayn/nuxt-bezier

### npm

https://www.npmjs.com/package/nuxt-bezier?activeTab=readme

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Can you open a PR @50rayn ?

**Comment by 50rayn** [comment]
@Atinux Sure. Sorry for that.
