### ISSUE TITLE
[Module Listing Request]: `nuxt-mailpit`

### ISSUE THREAD

**Issue by tdolsen** [nuxt/modules#889]
### Description

Simple module that integrates the [Mailpit](https://mailpit.axllent.org/) web UI in the Nuxt devtools.

### Repository

https://github.com/tdolsen/nuxt-mailpit

### npm

https://www.npmjs.com/package/nuxt-mailpit

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR for it?

**Comment by tdolsen** [comment]
Absolutely! (PR #891)
