### ISSUE TITLE
Add nuxt-appwrite

### ISSUE THREAD

**Issue by Hrdtr** [nuxt/modules#89]
Module repo:
https://github.com/Hrdtr/nuxt-appwrite

**Comment by Geminii** [comment]
Hi @Hrdtr 👋 
Could you provide me an icon (svg/png) of 40*40px to add your module ? 
Great work about your module 👍

**Comment by Hrdtr** [comment]
Here the icon [https://github.com/Hrdtr/nuxt-appwrite/raw/main/docs/static/icon.png](https://github.com/Hrdtr/nuxt-appwrite/raw/main/docs/static/icon.png)

Thank you @Geminii

**Comment by Hrdtr** [comment]
Ayee, sorry I'm forgot about that :'D  
I'll add a link to Appwrite later and add some short explanation about it.

For now, If someone see this issue and didn't have any idea about it. (Please see [https://appwrite.io](https://appwrite.io))  
Appwrite is an end-to-end backend server that is aiming to abstract the complexity of common, complex, and repetitive tasks required for building a modern app.
