### ISSUE TITLE
Are `@nuxt/test-utils` supported?

### ISSUE THREAD

**Issue by shinGangan** [nuxt/modules#895]
### Context

I think `@nuxt/test-utils` is one of the frameworks listed in the Monorepo Guide.

- https://nuxt.com/docs/community/framework-contribution#monorepo-guide

Unlike other Frameworks, `@nuxt/test-utils` is a module. Users need to add `@nuxt/test-utils/module` to `nuxt.config` file to use it, which is a feature of modules.
Therefore, it would be nice for users to be able to add modules with `nuxi module add test-utils`.

- https://nuxt.com/docs/getting-started/testing#setup

I would like to hear @danielroe 's opinion/policy on this since there are both aspects of framework, module, and both.
Since we have created an experimental branch, I would like to create a pull request if the policy is to add it.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### 📗 Note

The following commits have been experimentally configured. I can create a PR at any time.

- https://github.com/shinGangan/modules/commit/b831c7a8a5bcfaea1e3712cacca143922c378b6b

**Comment by danielroe** [comment]
Why not! Thank you ❤️

**Comment by shinGangan** [comment]
OK, I'll make a Pull Request right away. ❤️
I think the list of contributors is incomplete, so a review would be appreciated.
