### ISSUE TITLE
[Module Listing Request]: `nuxt-file-storage`

### ISSUE THREAD

**Issue by NyllRE** [nuxt/modules#926]
### Description

![Banner](https://raw.githubusercontent.com/NyllRE/nuxt-file-storage/HEAD/playground/public/nuxt-file-storage-banner.svg)

# Nuxt File Storage
I made a nuxt file storage solution for storing files and media in your nuxt project without having to rely on an alternative file storage solution. 

It is an easy solution to store files in your nuxt apps. Be able to upload files from the frontend and recieve them from the backend to then save the files in your project.

### Features
- Get files from file input and make them ready to send to backend
- Serialize files in the backend to be able to use them appropriately
- Store files in a specified location in your Nuxt backend with Nitro Engine

### Repository

https://github.com/NyllRE/nuxt-file-storage

### npm

https://www.npmjs.com/package/nuxt-file-storage

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Happy to open a PR @NyllRE ?

**Comment by NyllRE** [comment]
@Atinux definitely! I'll make sure to open one asap, and I really appreciate your approval that means a lot to me!

**Comment by NyllRE** [comment]
@Atinux I have just opened a PR for the package

**Comment by NyllRE** [comment]
this issue has been closed for [merging the module](https://github.com/nuxt/modules/pull/934)
