### ISSUE TITLE
Add nuxt-chiffre

### ISSUE THREAD

**Issue by tuarrep** [nuxt/modules#96]
Repo: https://github.com/chiffre-io/nuxt-chiffre

Description: ~~Anonymous~~ Privacy first E2E encrypted analytics

**Comment by tuarrep** [comment]
I've simply linked the repo linked in the npm page

>

**Comment by franky47** [comment]
Hi, I'm the maker of Chiffre, @rclement kindly contributed a Nuxt module for it, and I forked his repo in the chiffre-io organization for visibility and back-contribution. We should probably regard his as the "source of truth", and update the package.json to point to his repo instead, with his permission.

Side note: Chiffre is privacy-first, not anonymous. Technically: while there's no effort to identify visitors (and never will be), there's no effort either to truly anonymise them at this time. A more fitted description would be "Privacy-first end-to-end encrypted analytics".

**Comment by rclement** [comment]
Hi, thanks for including me!

Indeed, the main repo for the chiffre module is the one I maintain within my workspace.
However, I am open to transferring it to a more appropriate location: the only things that will require some fix-up will be Renovatebot integration and continuous delivery workflows with npm.js.

@franky47 do you want me to transfer it to @chiffre-io?

On another note: @Atinux is the new documentation convention using `nuxt/content` required for homogeneous Nuxt modules integration?

**Comment by franky47** [comment]
@rclement yes, we can transfer it to the @chiffre-io org, so that all integrations are in the same place. The NPM package will remain `nuxt-chiffre` for compatibility (packages in the chiffre-io org use the `@chiffre/*` scope on NPM, but it can be reserved for the app core packages).

**Comment by franky47** [comment]
The repo has been migrated, and now lives at https://github.com/chiffre-io/nuxt-chiffre.
