### ISSUE TITLE
[Module Listing Request]: `nuxt-ngrok`

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/modules#977]
### Description

Easily expose your Nuxt application to the internet with NGROK

### Repository

https://github.com/arashsheyda/nuxt-ngrok

### npm

https://npmjs.com/package/nuxt-ngrok

### Nuxt Compatibility

Nuxt 3

**Comment by Atinux** [comment]
Feel free to open a PR once the docs is ready (or at least a small example of the output in the console 😊 )

Love the work you do on the Nuxt modules @arashsheyda

**Comment by arashsheyda** [comment]
@Atinux sure, thanks 😃
